### ISSUE TITLE
[BUG] Unable to set env var default values within template config.

### ISSUE THREAD

**Issue by flancast90** [buildable/templates#42]
**Describe the bug**
Default env variable values cannot be set in ``config.json`` files for templates.

**Expected behavior**
The optimal environment variable creation process would allow a template creator to set a default value within the config file, which could then be edited as-needed by users. This would streamline actions such as using dynamic base URLs for APIs, as shown in @paulkr's comment in #41.  

**Example**
```json
"envVars": {
    "FAKE_API_KEY": "123456"
  },
```

**Comment by paulkr** [comment]
Since each environment variable has a value for the development (`test`) and production (`live`) environments, you have to specify both values in the configuration.

**Example:**
```json
{
  "envVars": {
    "FAKE_API_KEY": {
      "development": "fake-development-api-key",
      "production": "fake-production-api-key"
    }
  }
}
```
